---
tags: [spring-cloud, hystrix]
projects: [spring-cloud, spring-cloud-netflix]
---
:spring_version: current
:spring_boot_version: 1.2.8.RELEASE
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-circuit-breaker
本指南将带你一步一步了解，使用Netflix Hystrix 默认的容错库，为存在潜在错误的方法应用断路器。

== 你将构建什么

你会建立一个使用 http://martinfowler.com/bliki/CircuitBreaker.html[断路器模式] 优雅地将功能降级，当一个方法调用失败的时候。使用断路器模式可以让一个微服务在相关的服务失败时继续运行，防止失败的级联与给失败的服务恢复时间。


== 你需要什么

:java_version: 1.8
include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[reveal-gradle]]
[.reveal-gradle]
== 使用Gradle构建

[[scratch]]
[.use-gradle]
== 使用Gradle构建

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_system_intro.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_both_builds.adoc[]

`bookstore/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/webGoBetter/{project_id}/master/initial/bookstore/build.gradle[]
----

`reading/build.gradle`
// AsciiDoc source formatting doesn't support groovy, so using java instead
[source,java]
----
include::https://raw.githubusercontent.com/swebGoBetter/{project_id}/master/initial/reading/build.gradle[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-gradle-plugin.adoc[]

[[reveal-maven]]
[.reveal-maven]
== 使用Maven构建

[[use-maven]]
[.use-maven]
== 使用Maven构建

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/build_system_intro_maven.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/create_directory_structure_hello.adoc[]

`bookstore/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/webGoBetter/{project_id}/master/initial/bookstore/pom.xml[]
----

`reading/pom.xml`
[source,xml]
----
include::https://raw.githubusercontent.com/webGoBetter/{project_id}/master/initial/reading/pom.xml[]
----

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/spring-boot-maven-plugin.adoc[]

include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]
== 建立一个服务器端微服务应用

书店服务将有一个端点。它可以在 `/recommended` 中访问，并且（为了简单起见）返回一个 `String` 推荐阅读列表。

编辑我们的主类，在 `BookstoreApplication.java` 。应该是这样的：

`bookstore/src/main/java/hello/BookstoreApplication.java`
[source,java]
----
include::complete/bookstore/src/main/java/hello/BookstoreApplication.java[]
----

`@RestController` 注释标记 `BookstoreApplication` 作为一个控制器类，像 `@Controller` 一样，也确保 `@RequestMapping` 方法在这个类中的行为好像有 `@ResponseBody` 注解一样。那就是，在这类中的 `@RequestMapping` 方法的返回值将从原来的类型被自动转换成适当的类型然后将直接写入响应体。

我们将在客户端服务应用程序的本地运行此应用程序，因此在 `src/main/resources/application.properties` 属性中，设置 `server.port` ，以便当我们运行该服务时，书店服务不与客户端发生冲突。

`bookstore/src/main/resources/application.properties`
[source,properties]
----
include::complete/bookstore/src/main/resources/application.properties[]
----

== 建立一个客户端微服务应用

阅读应用程序将是我们对书店应用程序的前端。我们将可以在 `/to-read` 中查看我们的阅读列表，阅读列表将从书店服务应用程序获取数据。T

`reading/src/main/java/hello/ReadingApplication.java`
[source,java]
----
package hello;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.client.RestTemplate;
import java.net.URI;

@RestController
@SpringBootApplication
public class ReadingApplication {

  @RequestMapping("/to-read")
  public String readingList() {
    RestTemplate restTemplate = new RestTemplate();
    URI uri = URI.create("http://localhost:8090/recommended");

    return restTemplate.getForObject(uri, String.class);
  }

  public static void main(String[] args) {
    SpringApplication.run(ReadingApplication.class, args);
  }
}
----

为了从书店得到的列表，我们用春天的 `RestTemplate` 模板类。 `RestTemplate` 使用HTTP GET请求到书店服务的URL,这个是我们提供的URL,然后返回一个 `String`。（欲了解更多关于使用Spring使用REST式服务的信息，请参见下面的 http://knos.top/guides/gs/consuming-rest/[Consuming a RESTful Web Service] 指南）。

添加 `server.port` 属性到 `src/main/resources/application.properties`:

`reading/src/main/resources/application.properties`
[source,properties]
----
include::complete/reading/src/main/resources/application.properties[]
----

我们现在可以在浏览器中访问阅读应用程序上的 `/to-read` 端点，并查看我们的阅读列表。然而，由于我们依赖于书店应用程序，如果它发生了什么事情，或者如果阅读根本无法访问书店，我们将没有列表，我们的用户将得到一个讨厌的HTTP 500错误消息。

== 应用断路器模式

Netflix的Hystrix库提供的断路器模式的实现：当我们应用一个断路器到一种方法上，Hystrix会观察对该方法的失败调用，如果建立一个入口失败，Hystrix会打开电路，以便于随后自动调用失败处理。当电打开时，Hystrix 重定向调用的方法，他们会被传递到我们指定的回退方法。

Spring Cloud Netflix Hystrix 寻找任何法有 `@HystrixCommand` 注释的方，包在一个连接到断路器的代理中，使Hystrix可以监控这个方法。目前只在一个类有 `@Component` 或 `@Service` ，所以在阅读应用中，在 `src/main/java/hello`，添加一个新类：`BookService` 。

 `RestTemplate` 将在 `BookService` 创建时注入构造函数的。完整类应该如下所示：

`reading/src/main/java/hello/BookService.java`
[source,java]
----
include::complete/reading/src/main/java/hello/BookService.java[]
----

我们已经应用 `@HystrixCommand` 到我们原来的 `readingList()` 方法上。我们这里也有一个新的方法： `reliable()` 。 `@HystrixCommand` 标注 `reliable` 为作为他的 `fallbackMethod` ，如果因为某些原因，Hystrix打开 `readingList()` 上的电路，我们会为我们的用户准备了一个很好的（如果短的话）占位符阅读清单。

我们的主类， `ReadingApplication` ，我们将创建一个 `RestTemplate` 组件，注入到 `BookService` ，然后为我们的阅读清单调用它：

`reading/src/main/java/hello/ReadingApplication.java`
[source,java]
----
include::complete/reading/src/main/java/hello/ReadingApplication.java[]
----

现在，为了从书店服务检索列表，我们调用  `bookService.readingList()` 。你也会注意到我们已经将最后一个注释， `@EnableCircuitBreaker` ；有必要告诉Spring Cloud阅读应用程序使用断路器，使其监控、开放和关闭（在我们的案例中是通过Hystrix的行为提供（behavior supplied））。

== 试试

同时运行书店服务和阅读服务，然后打开一个浏览器访问阅读服务的 `localhost:8080/to-read`端点 。您应该看到完整的推荐阅读清单：

----
Spring in Action (Manning), Cloud Native Java (O'Reilly), Learning Spring Boot (Packt)
----

现在关闭书店应用程序。我们的名单来源消失，但多亏了Hystrix 和 Spring Cloud Netflix，我们有一个可靠简短的列表挺身而出；你应该看到：

----
Cloud Native Java (O'Reilly)
----

== 总结

祝贺你!您刚刚开发了一个Spring应用程序，它使用断路器模式来防止级联故障，并为潜在的失败调用提供回退行为。




include::https://raw.githubusercontent.com/webGoBetter/getting-started-macros/master/footer.adoc[]
